version: '3'
services:

  #PHP Service
  b1ex-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: b1ex
    container_name: b1ex-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  b1ex-webserver:
    image: nginx:alpine
    container_name: b1ex-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8000"  #8080 is post of real machine, 8000 is the posrt where NGNIX lisning
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local